### ISSUE TITLE
How to avoid Access-Control-Allow-Origin error on Android?

### ISSUE THREAD

**Issue by archsoso** [crosswalk-project/DEPRECATED-crosswalk-apk-generator#31]
My web app needs to access the internet and when I used the generator to build the app and run it, it reported Access-Control-Allow-Origin error. It seems it could get around by
setAllowUniversalAccessFromFileURLs(true). Don't know whether there is a configuration param to allow cross-domain access?
The following ticket seemed to disable the Cross-Origin request by default. How can I enable that?
https://github.com/crosswalk-project/crosswalk/pull/791

**Comment by iiitmahesh** [comment]
in ionic serve cors is working in browser but not working apk

. In the browser (using ionic serve) it was working properly , but in apk (using ionic build android ) it was not working........

cordova plugin add cordova-plugin-whitelist (I have added this puigin using CLI)

I have used these things in config.xml

ionic.project{
"name": "sampleApp",
"app_id": "a2fbab8f",
"proxies": [
{"path": "/api", "proxyUrl": "http://myserver/api"} ] }

**Comment by davidmaxwaterman** [comment]
Hi, iinm, you should be redirecting your question to the newer version of this tool, called 'crosswalk-app-tools' :

<https://github.com/crosswalk-project/crosswalk-app-tools>

A newer version of the grunt-crosswalk plugin is soon to be released that is based off the above work (it requires 0.7 which isn't released yet).

Please make sure they have taken account of your use-case.

@r0b5t4 fyi

**Comment by r0b5t4** [comment]
@davidmaxwaterman crosswalk-app-tools does not support ionic/cordova. I would suggest to use ionic's user support facilities.

**Comment by baleboy** [comment]
@iiitmahesh indeed this looks like a question for the Ionic project.

**Comment by davidmaxwaterman** [comment]
Yes, I agree that the Iconic specific questions should be redirected, but is there any documentation for how to avoid CORS issues as described in the earlier discussion that Elliot was involved with? IE, is there a setting in the manifest that can control the addition of the `setAllowUniversalAccessFromFileURLs(true)` line in the appropriate part of the Android java code?
I guess that's somewhat of a different question, but it would close this issue out completely in my mind. If that isn't supported, then that also ends this discussion :)

**Comment by r0b5t4** [comment]
You can modify MainActivity.java when using separate crosswalk-app create/build steps instead of one-shot crosswalk-pkg.

**Comment by johnymachine** [comment]
Not sure if related, but my ionic app in android sends header Origin: file//: which causes the server request to fail. I have set filters on apache side like this:

``` xml
<filter>  
<filter-name>CorsFilter</filter-name>  
  <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>  
</filter>  
<filter-mapping>  
  <filter-name>CorsFilter</filter-name>  
  <url-pattern>/*</url-pattern>  
</filter-mapping>
```

Can i make ionic to send ip instead? (that seems to work in browser) Or is thare some apache configuration that i am missing?

Thanks!

**Comment by mburger81** [comment]
Hi @archsoso @iiitmahesh @davidmaxwaterman, did you found a solution for that?!?
We try also to omit sending header Origin file:// we can not work on server side to allows CORS so we have to do this on app side!
Please help if you can. thx

**Comment by sunilrawat123** [comment]
I am facing same issue, but the ionic team does not  care for this. almost 80% people who are using ionic are suffering  from this issue.

why people should use Ionic. LOL

**Comment by cooljith91112** [comment]
> I am facing same issue, but the ionic team does not care for this. almost 80% people who are using ionic are suffering from this issue.
> 
> why people should use Ionic. LOL

FYI. CORS errors are there for a [reason](https://en.wikipedia.org/wiki/Same-origin_policy). It(CORS) should be enabled on the server, not on the client side.

Also, this is a deprecated repo. No one is going to reply.
