### ISSUE TITLE
Why was this abandoned in favor of make_apk.py?  Feat req, sorta

### ISSUE THREAD

**Issue by cmawhorter** [crosswalk-project/DEPRECATED-crosswalk-apk-generator#64]
Can an explanation be added to the readme?  I'm curious as this seems like the more natural existence for xwalk v python.

I'm getting by fine with other options, but... curious. =]

**Comment by siovene** [comment]
Funny how just over a year later, make_apk was deprecated and then removed from Crosswalk.

**Comment by baleboy** [comment]
Yes, because we finally found the time and people to do something (crosswalk-app-tools) that already a year ago was considered the right thing to do. Not sure what's funny in that.

**Comment by davidmaxwaterman** [comment]
I changed the notice on the main page for this repository to guide visitors to the crosswalk-app-tools : 

<https://github.com/crosswalk-project/crosswalk-app-tools>

Closing this. Thanks.

**Comment by cmawhorter** [comment]
Yay!
